name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify
        run: mvn test
      - name: Generuj Javadoc
        run: mvn javadoc:javadoc
      - name: Package the application into a JAR
        run: mvn package
      - name: Prepare artifact directory
        run: |
          mkdir -p artifact/javadoc
          cp -r target/site/apidocs/* artifact/javadoc/
      - name: Upload JAR and Javadoc artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: |
            target/*.jar
            artifact/javadoc
